import './globals.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import ClientLayout from './ClientLayout';
import { Amplify } from 'aws-amplify';
import config from '@/src/aws-exports';
//import config from '@/src/amplifyconfiguration.json';

Amplify.configure(config);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
